/*
 * generated by Xtext 2.25.0
 */
package de.tu_bs.cs.isf.cbc.textual.jdl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.tu_bs.cs.isf.cbc.textual.jdl.JdlDslRuntimeModule;
import de.tu_bs.cs.isf.cbc.textual.jdl.JdlDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JdlDslIdeSetup extends JdlDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JdlDslRuntimeModule(), new JdlDslIdeModule()));
	}
	
}
