/*
 * generated by Xtext 2.25.0
 */
package de.tu_bs.cs.isf.cbc.textual.jdl.ide;


/**
 * Use this class to register ide components.
 */
public class JdlDslIdeModule extends AbstractJdlDslIdeModule {
}
