/**
 * generated by Xtext 2.10.0
 */
package de.tu_bs.cs.isf.cbc.textual.tool.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class DslLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public DslLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final /* Condition */Object condition) {
    throw new Error("Unresolved compilation problems:"
      + "\nSmallRepetitionStatement cannot be resolved to a type."
      + "\nSmallRepetitionStatement cannot be resolved to a type."
      + "\nCompositionStatement cannot be resolved to a type."
      + "\nCompositionStatement cannot be resolved to a type."
      + "\nSelectionStatement cannot be resolved to a type."
      + "\nSelectionStatement cannot be resolved to a type."
      + "\nCbCFormula cannot be resolved to a type."
      + "\nCbCFormula cannot be resolved to a type."
      + "\neContainer cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\ninvariant cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nname cannot be resolved"
      + "\nguard cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nname cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\nintermediateCondition cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nname cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\nguards cannot be resolved"
      + "\ncontains cannot be resolved"
      + "\nguards cannot be resolved"
      + "\nindexOf cannot be resolved"
      + "\nname cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\npreCondition cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nname cannot be resolved"
      + "\npostCondition cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nname cannot be resolved");
  }
  
  public String text(final /* Variant */Object variant) {
    throw new Error("Unresolved compilation problems:"
      + "\nname cannot be resolved");
  }
  
  public String text(final /* SmallRepetitionStatementImpl */Object std) {
    return "Repetition Statement";
  }
  
  public String text(final /* CompositionStatementImpl */Object std) {
    return "Composition Statement";
  }
  
  public String text(final /* SelectionStatementImpl */Object std) {
    return "Selection Statement";
  }
  
  public String text(final /* MethodStatementImpl */Object std) {
    throw new Error("Unresolved compilation problems:"
      + "\nname cannot be resolved");
  }
  
  public String text(final /* AbstractStatementImpl */Object std) {
    throw new Error("Unresolved compilation problems:"
      + "\nname cannot be resolved");
  }
  
  public String text(final /* CbCFormula */Object formula) {
    throw new Error("Unresolved compilation problems:"
      + "\nname cannot be resolved");
  }
}
