/**
 * generated by Xtext 2.10.0
 */
package de.tu_bs.cs.isf.cbc.textual.tool.generator;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class DslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    throw new Error("Unresolved compilation problems:"
      + "\nJavaVariables cannot be resolved to a type."
      + "\nGlobalConditions cannot be resolved to a type."
      + "\nRenaming cannot be resolved to a type."
      + "\nCbCProblem cannot be resolved to a type."
      + "\nThe method or field JavaVariables is undefined"
      + "\nThe method or field JavaVariables is undefined"
      + "\nThe method or field GlobalConditions is undefined"
      + "\nThe method or field GlobalConditions is undefined"
      + "\nThe method or field Renaming is undefined"
      + "\nThe method or field Renaming is undefined"
      + "\nThe method or field CbCFormula is undefined"
      + "\nTraverseFormulaAndGenerate cannot be resolved."
      + "\nThe method traverseFormulaAndGenerate() is undefined for the type TraverseFormulaAndGenerate"
      + "\ncbcformula cannot be resolved");
  }
}
