/*
 * generated by Xtext 2.25.0
 */
package de.tu_bs.cs.isf.cbc.textual.jdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JdlDslUiModule extends AbstractJdlDslUiModule {

	public JdlDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
