/*
 * generated by Xtext 2.15.0
 */
package de.tu_bs.cs.isf.cbc.textual.tool.ui;

import com.google.inject.Injector;
import de.tu_bs.cs.isf.cbc.textual.tool.ui.internal.ToolActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ToolActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ToolActivator activator = ToolActivator.getInstance();
		return activator != null ? activator.getInjector(ToolActivator.DE_TU_BS_CS_ISF_CBC_TEXTUAL_TOOL_DSL) : null;
	}

}
