/*
 * generated by Xtext 2.25.0
 */
package de.tu_bs.cs.isf.cbc.textual.tool.ui;

import com.google.inject.Injector;
import de.tu_bs.cs.isf.cbc.textual.tool.ui.internal.ToolActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ToolActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ToolActivator activator = ToolActivator.getInstance();
		return activator != null ? activator.getInjector(ToolActivator.DE_TU_BS_CS_ISF_CBC_TEXTUAL_TOOL_DSL) : null;
	}

}
