/*
 * generated by Xtext 2.25.0
 */
package de.tu_bs.cs.isf.cbc.textual.jdl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JdlDslStandaloneSetup extends JdlDslStandaloneSetupGenerated {

	public static void doSetup() {
		new JdlDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
