/*
 * generated by Xtext 2.25.0
 */
package de.tu_bs.cs.isf.cbc.textual.jdl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JdlDslRuntimeModule extends AbstractJdlDslRuntimeModule {
}
