/**
 * generated by Xtext 2.10.0
 */
package de.tu_bs.cs.isf.cbc.textual.tool.validation;

import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DslValidator /* implements AbstractDslValidator  */{
  public static final String INVALID_NAME = "invalidName";
  
  public static final String NOT_PROVED = "notProved";
  
  @Check
  public Object checkSyntaxOfStatement(final /* AbstractStatement */Object statement) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field AbstractStatementImpl is undefined"
      + "\nThe method warning(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\nclass cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nname cannot be resolved"
      + "\n!= cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nname cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\n! cannot be resolved"
      + "\nname cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nABSTRACT_STATEMENT__NAME cannot be resolved");
  }
  
  @Check
  public Object checkSyntaxOfRetunrStatement(final /* ReturnStatement */Object statement) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ReturnStatementImpl is undefined"
      + "\nThe method warning(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\nclass cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nname cannot be resolved"
      + "\n!= cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nname cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\n! cannot be resolved"
      + "\nname cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nABSTRACT_STATEMENT__NAME cannot be resolved");
  }
  
  @Check
  public Object checkSyntaxOfCondition(final /* Condition */Object condition) {
    return null;
  }
  
  @Check(CheckType.EXPENSIVE)
  public Object checkProveOfStatement(final /* AbstractStatement */Object statement) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field AbstractStatementImpl is undefined"
      + "\nThe method or field CbCFormula is undefined"
      + "\nThe method traverseFormula(Object, AbstractStatement) is undefined for the type TraverseFormula"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\nclass cannot be resolved"
      + "\nequals cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nallContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nnext cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nABSTRACT_STATEMENT__PROVEN cannot be resolved");
  }
  
  @Check(CheckType.EXPENSIVE)
  public Object checkProveOfReturnStatement(final /* ReturnStatement */Object statement) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field CbCFormula is undefined"
      + "\nThe method traverseFormula(Object, ReturnStatement) is undefined for the type TraverseFormula"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\neResource cannot be resolved"
      + "\nallContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nnext cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nABSTRACT_STATEMENT__PROVEN cannot be resolved");
  }
  
  @Check(CheckType.EXPENSIVE)
  public Object checkProveOfStrengthWeakStatement(final /* StrengthWeakStatement */Object statement) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field CbCFormula is undefined"
      + "\nThe method traverseFormula(Object, StrengthWeakStatement) is undefined for the type TraverseFormula"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\neResource cannot be resolved"
      + "\nallContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nnext cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nABSTRACT_STATEMENT__PROVEN cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nABSTRACT_STATEMENT__PROVEN cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nABSTRACT_STATEMENT__PROVEN cannot be resolved");
  }
  
  @Check(CheckType.EXPENSIVE)
  public Object checkProveOfMethodStatement(final /* MethodStatement */Object statement) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field CbCFormula is undefined"
      + "\nThe method traverseFormula(Object, MethodStatement) is undefined for the type TraverseFormula"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\neResource cannot be resolved"
      + "\nallContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nnext cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nABSTRACT_STATEMENT__PROVEN cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nABSTRACT_STATEMENT__PROVEN cannot be resolved");
  }
  
  @Check(CheckType.EXPENSIVE)
  public Object checkProveOfSkipStatement(final /* SkipStatement */Object statement) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field CbCFormula is undefined"
      + "\nThe method traverseFormula(Object, SkipStatement) is undefined for the type TraverseFormula"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\neResource cannot be resolved"
      + "\nallContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nnext cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nABSTRACT_STATEMENT__PROVEN cannot be resolved");
  }
  
  @Check(CheckType.EXPENSIVE)
  public Object checkProveOfRepetitionStatement(final /* SmallRepetitionStatement */Object statement) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field CbCFormula is undefined"
      + "\nThe method traverseFormula(Object, SmallRepetitionStatement) is undefined for the type TraverseFormula"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\neResource cannot be resolved"
      + "\nallContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nnext cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nSMALL_REPETITION_STATEMENT__PRE_PROVEN cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nSMALL_REPETITION_STATEMENT__POST_PROVEN cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nSMALL_REPETITION_STATEMENT__VARIANT_PROVEN cannot be resolved");
  }
  
  @Check(CheckType.EXPENSIVE)
  public Object checkProveOfSelectionStatement(final /* SelectionStatement */Object statement) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field CbCFormula is undefined"
      + "\nThe method traverseFormula(Object, SelectionStatement) is undefined for the type TraverseFormula"
      + "\nThe method info(String, Object, String) is undefined"
      + "\nThe method or field CbcmodelPackage is undefined"
      + "\neResource cannot be resolved"
      + "\nallContents cannot be resolved"
      + "\nfilter cannot be resolved"
      + "\nnext cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nURI cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nSELECTION_STATEMENT__PRE_PROVE cannot be resolved");
  }
}
