/*
 * generated by Xtext 2.15.0
 */
package de.tu_bs.cs.isf.cbc.textual.tool.scoping;

import jbase.scoping.JbaseScopeProvider;

public abstract class AbstractDslScopeProvider extends JbaseScopeProvider {
}
